CodePage/Models/Student.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Models
{
    public class Student:BaseEntity
    {
        [Required, MaxLength(200)]
        public string FullName { get; set; }
        [Required]
        public string Mail { get; set; }
        [Required]
        public string Number { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public int CAP { get; set; }
        public int GroupId { get; set; }
        public Group Group { get; set; }
        public List<Grade> Grades { get; set; }
    }
}

CodePage/Areas/Admin/Controllers/GradeController.cs
using CodePage.DAL;
using CodePage.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CodePage.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Teacher")]
    public class GradeController : Controller
    {
        private readonly AppDbContext db;
        private readonly SignInManager<AppUser> signInManager;

        public GradeController(AppDbContext _db, SignInManager<AppUser> _signInManager)
        {
            db = _db;
            signInManager = _signInManager;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null) return RedirectToAction("Index", "Student");
            return View(await db.Students.Include(x=> x.Grades).FirstOrDefaultAsync(x => x.Id == id));
        }
        public IActionResult Add()
        {
            ViewData["StudentId"] = new SelectList(db.Students, "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(Grade grade)
        {
            if (ModelState.IsValid)
            {
                if(grade.Mark<=100 && grade.Mark >= 0)
                {
                    grade.CreateDate = DateTime.Now;
                    grade.UpdateDate = DateTime.Now;
                    grade.TeacherId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    await db.Grades.AddAsync(grade);
                    await db.SaveChangesAsync();
                    Student student =await db.Students.FirstOrDefaultAsync(x => x.Id == grade.StudentId);
                    int count = db.Grades.Where(x => x.StudentId == grade.StudentId).Count();
                    student.CAP = ((student.CAP*(count-1) + grade.Mark)/count);
                    db.Students.Update(student);
                    db.SaveChanges();
                }
                else
                {
                    ModelState.AddModelError("Mark", "Mark cannot be more than 100 or less than 0");
                    ViewData["StudentId"] = new SelectList(db.Students, "Id", "FullName");
                    return View();
                }
            }
            return RedirectToAction("Index", "Student");
        }
    }
}

CodePage/Areas/Admin/Controllers/StudentController.cs
using bauen.Utils;
using CodePage.DAL;
using CodePage.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class StudentController : Controller
    {
        private readonly AppDbContext db;
        private readonly IWebHostEnvironment env;
        public StudentController(AppDbContext _db, IWebHostEnvironment _env)
        {
            db = _db;
            env = _env;
        }
        public async Task<IActionResult> Index()
        {
            return View(await db.Students.Include(x=>x.Group).ToListAsync());
        }
        public IActionResult Add()
        {
            ViewData["GroupId"] = new SelectList(db.Groups, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(Student student)
        {
            if (ModelState.IsValid)
            {
                Student duplicate = await db.Students.FirstOrDefaultAsync(x => x.Mail == student.Mail);
                if (duplicate == null)
                {
                    student.CreateDate = DateTime.Now;
                    student.UpdateDate = DateTime.Now;
                    student.Image = await student.ImageFile.Upload(env.WebRootPath, @"img/students");
                    await db.Students.AddAsync(student);
                    await db.SaveChangesAsync();
                    Group groupToAddStudentTo= await db.Groups.FirstOrDefaultAsync(x => x.Id == student.GroupId);
                    groupToAddStudentTo.StudentCount++;
                    await db.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index", "Student");
        }
        public async Task<IActionResult> Details(int? id)
        {
            return View(await db.Students.Include(x => x.Group).FirstOrDefaultAsync(x=> x.Id==id));
        }
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["GroupId"] = new SelectList(db.Groups, "Id", "Name");
            return View(await db.Students.Include(x => x.Group).FirstOrDefaultAsync(x => x.Id == id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Student student)
        {
            if (ModelState.IsValid)
            {
                student.UpdateDate = DateTime.Now;
                if (student.ImageFile != null)
                {
                    student.Image = await student.ImageFile.Upload(env.WebRootPath, @"img/students");
                }
                db.Students.Update(student);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Student");
        }
        public async Task<IActionResult> Delete(int? id)
        {
            return View(await db.Students.Include(x => x.Group).FirstOrDefaultAsync(x => x.Id == id));
        }
        public async Task<IActionResult>  DeleteConfirmed(int? id)
        {
            if (!ModelState.IsValid) RedirectToAction("Index", "Student");
            Student student = await db.Students.FirstOrDefaultAsync(x => x.Id == id);
            db.Students.Remove(student);
            student.Image = await student.ImageFile.Upload(env.WebRootPath, @"img/students");
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Student");
        }
    }
}

CodePage/Controllers/StudentController.cs
using CodePage.DAL;
using CodePage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Controllers
{
    public class StudentController : Controller
    {
        private readonly AppDbContext db;
        public StudentController(AppDbContext _db)
        {
            db = _db;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null) return RedirectToAction("Index", "Group");
            ViewBag.Group = db.Groups.Include(x=> x.Category).FirstOrDefault(x => x.Id == id);
            return View(await db.Students.Include(x=> x.Group).Include(x=> x.Group.TeacherToGroups).ThenInclude(x => x.Teacher).Where(x=> x.GroupId==id).ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return RedirectToAction("Index", "Group");
            return View(await db.Students.Include(x => x.Group).Include(x => x.Group.Category).Include(x => x.Group.TeacherToGroups).ThenInclude(x => x.Teacher).FirstOrDefaultAsync(x => x.Id == id));
        }
    }
}

CodePage/Areas/Admin/Views/Student/Add.cshtml
@model Student
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add Category</h6>
    </div>
    <div class="card-body">
        <form asp-action="Add" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-4 mb-4">
                    <label asp-for="FullName"></label>
                    <input class="form-control" asp-for="FullName">
                    <span class="text-danger small" asp-validation-for="FullName"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="Mail"></label>
                    <input class="form-control" asp-for="Mail">
                    <span class="text-danger small" asp-validation-for="Mail"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="Number"></label>
                    <input class="form-control" asp-for="Number">
                    <span class="text-danger small" asp-validation-for="Number"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="ImageFile"></label>
                    <input class="form-control" asp-for="ImageFile">
                    <span class="text-danger small" asp-validation-for="ImageFile"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GroupId" class="control-label">Group</label>
                    <select asp-for="GroupId" class="form-control" asp-items="ViewBag.GroupId"></select>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-success">Save</button>
                    <a asp-action="Index" class="btn btn-primary">Go Back</a>
                </div>
            </div>
        </form>
    </div>
</div>


@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Description'))
            .catch(error => {
                console.error(error);
            });
    </script>
    <style>
        .ck-editor__editable {
            min-height: 200px;
        }
    </style>
}

CodePage/Areas/Admin/Views/Student/Delete.cshtml
@model Student
<div class="row">
    <div class="col-md-8">
        <img src="~/img/students/@Model.Image" width="200px" style="border-radius: 100%" />
        <h4>Name: <b>@Model.FullName</b></h4>
        <h4>Mail: <b>@Model.Mail</b></h4>
        <h4>Number: <b>@Model.Number</b></h4>
        <h4>CAP: <b>@Model.CAP</b></h4>
        <h4>Group: <b>@Model.Group.Name</b></h4>
        <a asp-action="Index" class="btn btn-primary">Go Back</a>
        <a asp-action="DeleteConfirmed" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
    </div>
</div>

CodePage/Areas/Admin/Views/Student/Details.cshtml
@model Student
<div class="row">
    <div class="col-md-8">
        <img src="~/img/students/@Model.Image" width="200px" />
        <h4>Name: <b>@Model.FullName</b></h4>
        <h4>Mail: <b>@Model.Mail</b></h4>
        <h4>Number: <b>@Model.Number</b></h4>
        <h4>CAP: <b>@Model.CAP</b></h4>
        <h4>Group: <b>@Model.Group.Name</b></h4>
        <a asp-action="Index" class="btn btn-primary">Go Back</a>
    </div>
</div>

CodePage/Areas/Admin/Views/Student/Edit.cshtml
@model Student
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add Category</h6>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-4 mb-4">
                    <label asp-for="FullName"></label>
                    <input class="form-control" asp-for="FullName">
                    <span class="text-danger small" asp-validation-for="FullName"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="Mail"></label>
                    <input class="form-control" asp-for="Mail">
                    <span class="text-danger small" asp-validation-for="Mail"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="Number"></label>
                    <input class="form-control" asp-for="Number">
                    <span class="text-danger small" asp-validation-for="Number"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="CAP"></label>
                    <input class="form-control" asp-for="CAP">
                    <span class="text-danger small" asp-validation-for="CAP"></span>
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="ImageFile"></label>
                    <input class="form-control" asp-for="ImageFile">
                    <span class="text-danger small" asp-validation-for="ImageFile"></span>
                    <input type="hidden" asp-for="Image"  />
                </div>
                <div class="form-group">
                    <label asp-for="GroupId" class="control-label">Group</label>
                    <select asp-for="GroupId" class="form-control" asp-items="ViewBag.GroupId"></select>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-success">Save</button>
                    <a asp-action="Index" class="btn btn-primary">Go Back</a>
                </div>
            </div>
        </form>
    </div>
</div>


@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Description'))
            .catch(error => {
                console.error(error);
            });
    </script>
    <style>
        .ck-editor__editable {
            min-height: 200px;
        }
    </style>
}

CodePage/Areas/Admin/Views/Student/Index.cshtml
@model List<Student>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Categories</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>Mail</th>
                        <th>Number</th>
                        <th>CAP</th>
                        <th>Group</th>
                        <th>Grade</th>
                        <th>Settings</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Full Name</th>
                        <th>Mail</th>
                        <th>Number</th>
                        <th>CAP</th>
                        <th>Group</th>
                        <th>Grade</th>
                        <th>Settings</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (Student item in Model)
                    {
                        <tr>
                            <td>@item.FullName</td>
                            <td>@item.Mail</td>
                            <td>@item.Number</td>
                            <td>@item.CAP</td>
                            <td>@item.Group.Name</td>
                            <th>
                                <a asp-controller="Grade" asp-action="Index" asp-route-id="@item.Id" class="btn btn-primary mr-1">
                                    Grades
                                </a>
                            </th>
                            <td>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary mr-1">
                                    <i class="fas fa-eye"></i>
                                </a>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning mr-1">
                                    <i class="fas fa-fw fa-wrench"></i>
                                </a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mr-1">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>