CodePage/Controllers/AboutUsController.cs
using CodePage.DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly AppDbContext db;
        public AboutUsController(AppDbContext _db)
        {
            db = _db;
        }
    }
}

CodePage/Controllers/GroupController.cs
using CodePage.DAL;
using CodePage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Controllers
{
    public class GroupController : Controller
    {
        private readonly AppDbContext db;
        public GroupController(AppDbContext _db)
        {
            db = _db;
        }
        public IActionResult Index(int? id)
        {
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Category = id;
            if (id != null)
            {
                return View(db.Groups.Include(x => x.Category).Include(x => x.TeacherToGroups).ThenInclude(x=>x.Teacher).Where(x => x.CategoryId == id).ToList());
            }
            return View(db.Groups.Include(x => x.Category).Include(x => x.TeacherToGroups).ToList());
            
        }
    }
}

CodePage/Controllers/HomeController.cs
using CodePage.DAL;
using CodePage.HomeViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext db;
        public HomeController(AppDbContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            ViewBag.Color = 0;
            ViewModel vm = new ViewModel()
            {
                Banners=db.Banners.ToList(),
                Categories=db.Categories.ToList(),
                AboutUs=db.AboutUs.ToList(),
            };
            return View(vm);
        }
    }
}

CodePage/Controllers/MessageController.cs
using CodePage.DAL;
using CodePage.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodePage.Controllers
{
    public class MessageController : Controller
    {
        private readonly AppDbContext db;
        public MessageController(AppDbContext _db)
        {
            db = _db;
        }
        public IActionResult Add(string Name, string Surname, string NumberBeginning, string Number, string Department)
        {
            if (Name != null && Surname!=null && Number != null)
            {
                Message ms = new Message()
                {
                    Name = Name,
                    Surname = Surname,
                    Number = NumberBeginning + Number,
                    Department = Department,
                    CreateDate = DateTime.Now,
                    UpdateDate = DateTime.Now,
                };
                db.Messages.Add(ms);
                db.SaveChanges();
                TempData["messageAdded"] = "Your message was added successsfully";
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

CodePage/Views/Home/Index.cshtml
@model ViewModel
<section id="banner" class="owl-carousel">
    @foreach (Banner item in Model.Banners)
    {
        <div class="banner-item" style="background-color: @item.Color;">
            <div class="container">
                <div class="row banner-wrapper">
                    <div class="d-flex align-items-center py-5">
                        <div class="col-md-8">
                            <h1 class="banner-heading">@item.Title</h1>
                            <p class="banner-text">@item.Subtitle</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>
<section id="education">
    <div class="container">
        <div class="row" style="height: 100vh;">
            <div class="d-flex align-items-center">
                <div class="col-md-6">
                    <div class="education-text py-5 designed">
                        <h2>tədris</h2>
                        <h3>sahələri</h3>
                        <img src="images/sep-line.png" alt="">
                        <p>İnformasiya Texnologiyaları sahəsində bugünün və gələcəyin ən tələb edilən istiqamətləri</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="container">
                        <div class="row">
                            @foreach (Category item in Model.Categories)
                            {
                                <div class="col-6 ed-category-wrapper ed-category-@(ViewBag.Color<5?(ViewBag.Color+=1):((ViewBag.Color-=4))) ed-category">
                                    <a asp-controller="Group" asp-action="Index" asp-route-id="@item.Id">
                                        <div>
                                            <img src="~/images/@item.Image">
                                            <h4>@item.Name</h4>
                                        </div>
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="why">
    <div class="container pb-5">
        <div class="row" style="height: 80vh;">
            <div class="d-flex align-items-center">
                <div class="col-md-6">
                    <div class="why-text py-5 designed">
                        <h3>niyə</h3>
                        <h2>code academy?</h2>
                        <img src="images/sep-line.png" alt="">
                        <p>Biz dərsləri Zəmanətli Təhsil Sistemi ilə Beynəlxalq Sertifikasiya imtahanlarının kurrikulumu əsasında keçirik. Talant Mərkəzi, Mentor Sistemi kimi özəlliklər və müasir tədris metodları ilə onlara praktiki məşğələlər təklif edirik.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach (AboutUs item in Model.AboutUs)
            {
                <div class="col-md-6 pb-4">
                    <div class="row card-item">
                        <div class="col-6">
                            <div class="image">
                                <img src="~/img/aboutUs/@item.Image" class="w-100">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="text">
                                <h5>@item.Title</h5>
                                <p>@Html.Raw(item.Text.Substring(0, 200))...</p>
                                <a asp-controller="AboutUs" asp-action="Index" asp-route-id="@item.Id">Ətraflı</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>
</section>
<section id="contact">
    <div class="container">
        <div class="row" style="height: 100vh;">
            <div class="d-flex align-items-center">
                <div class="col-md-5">
                    <div class="contact-text py-5 designed">
                        <h3>sualın var?</h3>
                        <h2 class="px-5">gəl görüşək!</h2>
                        <p class="px-5">Yüz dəfə eşitməkdənsə, bir dəfə görmək yaxşıdır. Bizimlə görüş təyin et, dərslərimiz, müəllimlərimiz və tədris prosesimizlə şəxsən tanış ol.</p>
                    </div>
                </div>
                <div class="col-md-5">
                    <form class="row g-3" asp-controller="Message" asp-action="Add" method="post">
                        <div class="col-6">
                            <input class="styleInput" type="text" placeholder="Ad" name="Name">
                        </div>
                        <div class="col-6">
                            <input class="styleInput" type="text" placeholder="Soyad" name="Surname">
                        </div>
                        <div class="col-3">
                            <select name="NumberBeginning" id="">
                                <option value="051">051</option>
                                <option value="050">050</option>
                                <option value="055">055</option>
                                <option value="077">077</option>
                                <option value="070">070</option>
                            </select>
                        </div>
                        <div class="col-9">
                            <input class="styleInput" type="text" placeholder="XXX-XX-XX" name="Number">
                        </div>
                        <div class="col-12">
                            <select name="Department" id="">
                                <option value="Şəbəkə Administratorluğu">Şəbəkə Administratorluğu</option>
                                <option value="IT Helpdesk">IT Helpdesk</option>
                                <option value="UI/UX">UI/UX</option>
                                <option value="2D">2D</option>
                                <option value="Full Stack Programming">Full Stack Programming</option>
                            </select>
                        </div>
                        <div class="col-12">
                            <button type="submit">Muraciet et</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>